apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: quibly
data:
  NODE_ENV: "production"
  PORT: "5000"
  SERVER_ID: "k8s-backend"
  # Using wildcard for testing with IP - Update with domain later
  FRONTEND_URL: "*"
  CORS_ORIGIN: "*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: quibly
data:
  # Update these with your Node IP after deployment
  # Format: http://<NODE_IP>:30500/api
  # Example: http://52.23.45.67:30500/api
  NEXT_PUBLIC_API_URL: "http://43.205.254.198:30500/api"
  NEXT_PUBLIC_SOCKET_URL: "http://43.205.254.198:30500"
  NEXT_PUBLIC_LIVEKIT_WS_URL: "wss://discord-7uox6c1m.livekit.cloud"
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: "463308873117-t8fmjs959c1d799d354cdts710tmic3h.apps.googleusercontent.com"
  NODE_ENV: "production"
